Employee/urls.py
from django.urls import path
from.import views

urlpatterns = [
    # path('home/', views.home,name="home"),
    path('dashboard/', views.dashboard,name="dashboard"),

    path('saveemployee/', views.saveemployee,name="saveemployee"),
    path('employees/', views.employees,name="employees"),
    path('delete_emp/<int:employee_id>', views.delete_emp,name="delete_emp"),
    path('update_emp/<int:employee_id>', views.update_emp,name="update_emp"),

    path('playerview/', views.playerview,name="playerview"),
    path('delete_player/<int:player_id>', views.delete_player,name="delete_player"),
    path('update_player/<int:player_id>', views.update_player,name="update_player"), 
    path('playeradd/', views.addplayer,name="playeradd"),  

    path('kitview/', views.kitview,name="kitview"),
    path('delete_kit/<int:kit_id>', views.delete_kit,name="delete_kit"),
    path('update_kit/<int:kit_id>', views.update_kit,name="update_kit"), 
    path('kitadd/', views.addkit,name="kitadd"), 
]

api/urls.py
from django.urls import path
from.import views

urlpatterns = [
    path('players/', views.PlayerListCreate.as_view(),name="players-list"),
    path('players/<int:pk>', views.PlayerRetrieveUpdateDestory.as_view(), name="players-all")
]

my_tennis_club/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('members.urls')),
    path('emp/', include('Employee.urls')),  
    path('api/', include('api.urls')),   
]

Employee/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    employee_id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=50)
    email=models.EmailField()
    contact=models.CharField(max_length=10)

    #this tell djdango the name of the table if you dont want to go with the default 
    class Meta:
        db_table="employee"

    # def __str__(self):
    #     return self.name

members/models.py
from django.db import models

# Create your models here.
# Below we create 5 models for our club web application,



# Trainer Model - will store data for club Trainers
class Trainer(models.Model):
    trainer_id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=30)
    address=models.CharField(max_length=50)
    city=models.CharField(max_length=60)
    state_province=models.CharField(max_length=30)
    country=models.CharField(max_length=50)
    website=models.URLField()
    email=models.EmailField()
    def __str__(self) :
        return self.name
    
# Club Model - will store data for different club names within the larger tennis club
class Club (models.Model):
    clud_id=models.AutoField(primary_key=True)
    club_name=models.CharField(max_length=30)
    def __str__(self) :
        return self.club_name
    
# Player Model - This model will store Player details, including Foreign Keys for Trainer and Clun they belong
class Player (models.Model):
    player_id=models.AutoField(primary_key=True)
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    age=models.IntegerField()
    address=models.CharField(max_length=50)
    email=models.EmailField()
    trainer_id=models.ForeignKey(Trainer, on_delete=models.CASCADE)
    club_id=models.ForeignKey( Club, on_delete=models.CASCADE)
    dob=models.DateField()
    def __str__(self):
        return self.first_name

# Payment Model - will be used in storing Player payments details
class Payment(models.Model):
    payment_id=models.AutoField(primary_key=True)
    month=models.CharField(max_length=30)
    paid_for=models.CharField(max_length=30)
    amount=models.IntegerField()
    player_id=models.ForeignKey(Player, on_delete=models.CASCADE)
    def __str__(self):
        return self.paid_for
    
# TrainingKitCollection Model - will store data on Training Kits collection by players
class TrainingKitCollection(models.Model):
    kit_id = models.AutoField(primary_key=True)
    kit_name = models.CharField(max_length=30)
    player_id = models.ForeignKey(Player, on_delete=models.CASCADE)
    collection_date = models.DateField()
    
    def __str__(self):
        return self.kit_name 

Employee/forms.py
from django import forms
from .models import Employee
from members.models import *

class EmployeeForm(forms.ModelForm):
    #this is an inner class within EmployeeForm that provide metadata for the form
    class Meta:
        #This specifies the specific model that will be associated with the form
        model=Employee
        #'all 'specifies the model fields from the Employee model
        fields="__all__"

class TrainerForm(forms.ModelForm):
    #this is an inner class within EmployeeForm that provide metadata for the form
    class Meta:
        #This specifies the specific model that will be associated with the form
        model=Trainer
        #'all 'specifies the model fields from the Employee model
        fields="__all__"

class PlayerForm(forms.ModelForm):
    #this is an inner class within EmployeeForm that provide metadata for the form
    class Meta:
        #This specifies the specific model that will be associated with the form
        model=Player
        #'all 'specifies the model fields from the Employee model
        fields="__all__"

class PaymentForm(forms.ModelForm):
    #this is an inner class within EmployeeForm that provide metadata for the form
    class Meta:
        #This specifies the specific model that will be associated with the form
        model=Payment
        #'all 'specifies the model fields from the Employee model
        fields="__all__"
class TrainingKitCollectionForm(forms.ModelForm):
    #this is an inner class within EmployeeForm that provide metadata for the form
    class Meta:
        #This specifies the specific model that will be associated with the form
        model=TrainingKitCollection
        #'all 'specifies the model fields from the Employee model
        fields="__all__"
        widgets = {
            'collection_date': forms.DateInput(attrs={'type': 'date'})
        }

Employee/views.py
from django.shortcuts import render, redirect
from .forms import * 
from .models import Employee
from members.models import *
from django.contrib import messages
from django.db.models import Count, Sum
# Create your views here.
def saveemployee(request):
    if request.method== "POST":
        form=EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect("employees")
            except:
                pass
    else:
        form=EmployeeForm()
        return render(request,'saveemp.html',{'form':form})

def employees(request):
        employees = Employee.objects.all()
        return render(request, "employees.html", {'employees': employees})

def delete_emp(request,employee_id):
    try:
        employee = Employee.objects.get(employee_id=employee_id)
        employee.delete()
        messages.success(request, 'Employee has been deleted successfully.')
        return redirect('employees')
    except Employee.DoesNotExist:
        messages.error(request, 'Employee does not exist.')
        return redirect('employees')

def update_emp(request,employee_id):
    if request.method=='POST':
        print('the id is:', employee_id)
        employee= Employee.objects.get(employee_id=employee_id)
        print(employee)
        
        form= EmployeeForm(request.POST,instance=employee)
        print(form)
        if form.is_valid():
            form.save()
            messages.success(request, 'Update Successful.')
            return redirect('employees')
        else:
            messages.error(request, 'Update failed.')
            return redirect('employees')
    else:
        employee = Employee.objects.get(employee_id=employee_id)
        return render(request,"updateemp.html",{'employee':employee})


#kit 
def kitview(request):
        kit = TrainingKitCollection.objects.all()
        return render(request, "kitview.html", {'kits': kit})
    
def addkit(request):
    if request.method == "POST":
        form = TrainingKitCollectionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("kitview") 
        else:
            pass # Redirect to a view named 'kitview' upon successful form submission
    else:
        form = TrainingKitCollectionForm()
    return render(request, 'kitadd.html', {'form': form})

def update_kit(request,kit_id):
    kit= TrainingKitCollection.objects.get(kit_id=kit_id)  
    if request.method=='POST':      
        form= TrainingKitCollectionForm(request.POST,instance=kit)
        print('first test')
        
        if form.is_valid():
            print('form test')
            form.save()
            messages.success(request, 'Update Successful.')
            return redirect('kitview')
        else:
            print(form.errors)
            messages.error(request, 'Update failed.')
            return redirect('kitview')
    else:
        player=Player.objects.all()
        return render(request,"kitupdate.html",{'kit':kit,'players':player})


def delete_kit(request,kit_id):
    try:
        kit = TrainingKitCollection.objects.get(kit_id=kit_id)
        kit.delete()
        messages.success(request, 'Kit has been deleted successfully.')
        return redirect('kitview')
    except kit.DoesNotExist:
        messages.error(request, 'kit does not exist.')
        return redirect('kitview')


# Player
def playerview(request):
        player = Player.objects.all()
        return render(request, "playerview.html", {'players': player})

def addplayer(request):
    if request.method== "POST":
        form=PlayerForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect("playerview")
            except:
                pass
    else:
        form=PlayerForm()
        return render(request,'playeradd.html',{'form':form})

def update_player(request,player_id):
    if request.method=='POST':
        player= Player.objects.get(player_id=player_id)
        
        form= PlayerForm(request.POST,instance=player)
        print(form)
        if form.is_valid():
            form.save()
            messages.success(request, 'Update Successful.')
            return redirect('playerview')
        else:
            messages.error(request, 'Update failed.')
            return redirect('playerview')
    else:
        player = Player.objects.get(player_id=player_id)
        club=Club.objects.all()
        trainer=Trainer.objects.all()
        return render(request,"playerupdate.html",{'player':player,'clubs':club,'trainers':trainer})


def delete_player(request,player_id):
    try:
        employee = Player.objects.get(player_id=player_id)
        employee.delete()
        messages.success(request, 'Player has been deleted successfully.')
        return redirect('playerview')
    except Player.DoesNotExist:
        messages.error(request, 'Player does not exist.')
        return redirect('playerview')


def dashboard(request):
    players= Player.objects.aggregate(player_count=Count('player_id'))
    player_count=players['player_count']

    employees= Employee.objects.aggregate(employees_count=Count('employee_id'))
    employees_count=employees['employees_count']

    payments= Payment.objects.aggregate(payment_sum=Sum('amount'))
    payment_sum=payments['payment_sum']

    return render(request, "dashboard.html",{'player_count':player_count,"employees_count":employees_count,"payment_sum":payment_sum})

Employee/templates/dashboard.html
{% extends 'sidebar.html'%} {% block content %}
<style>
    .cardbg1 {
        background-color: rgba(18, 116, 197, 0.774);
        color: rgb(235, 239, 243);
        margin: 10px;
    }

    .cardbg2 {
        background-color: rgba(78, 91, 116, 0.774);
        color: rgb(235, 239, 243);
        margin: 10px;
    }
</style>
<div class="container-fluid">
    <h1 class="text-info mt-5 mb-3">Dashboard</h1>
    <section class="row">
        <div class="card cardbg1 col-md-3">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-9">
                        <h4>Registered</h4>
                        <h5>Employees</h5>
                    </div>
                    <div class="col-md-3">
                        <i class="fas fa-user fa-fw me-3" style="font-size: xx-large; text-align: left"></i>
                        <span style="font-size: xx-large; text-align: right">{{player_count}}</span>
                    </div>
                </div>
                <div></div>
            </div>
        </div>

        <div class="card cardbg2 col-md-3">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-9">
                        <h4>Registered</h4>
                        <h5>players</h5>
                    </div>
                    <div class="col-md-3">
                        <i class="fas fa-user fa-fw me-3" style="font-size: xx-large; text-align: left"></i>
                        <span style="font-size: xx-large; text-align: right">{{employees_count}}</span>
                    </div>
                    <div></div>
                </div>
            </div>
        </div>

        <div class="card cardbg1 col-md-3">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <h4>Total</h4>
                        <h5>Amount</h5>
                    </div>
                    <div class="col-md-6">
                        <i class="fas fa-user fa-fw me-3" style="font-size: xx-large; text-align: left"></i> <br>
                        <span style="font-size: x-large; text-align: right">{{payment_sum}}</span>
                    </div>
                </div>
                <div></div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

Employee/templates/employees.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Employee's table</title>
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<style>
/* Custom CSS */
/* You can customize the table appearance further with your own CSS styles */
.table-striped tbody tr:nth-of-type(odd) {
background-color: whitesmoke;
}

.table-striped tbody tr:hover {
background-color: whitesmoke;
}

.btn-action {
margin-right: 5px;
}
</style>
{% extends 'sidebar.html' %}
</head>
<body>
    {% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>{{message}}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %} 

<div class="container">
    <h2>Employee's details</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Employee ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Contacts</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for employee in employees %}
            <tr>                
                <td>{{employee.employee_id}}</td>
                <td>{{employee.name}}</td>
                <td>{{employee.email}}</td>
                <td>{{employee.contact}}</td>
                <td>
                    <a href="{% url 'update_emp' employee.employee_id %}" class="btn btn-primary">update</a>
                    <a href="{% url 'delete_emp' employee.employee_id %}" class="btn btn-danger" onclick="confirmDelete()">delete</a>
                </td>
            </tr>          
            {% endfor %}
        </tbody>
    </table>
        <a href="{% url 'saveemployee'%}" class="btn btn-lg btn-outline-primary fas fa-plus">Add Employee</a>
    <script>
    function confirmDelete() {
    if (confirm("Are you sure you want to delete this employee?")) {
    document.getElementById(`delete-form-${employeeid}-${employeeid}`).submit();
    }
    }
    </script>


    

    </div>

{% endblock %}

</body>
</html>

Employee/templates/header.html
<form class="d-none d-md-flex input-group w-auto my-auto">
    <input
           autocomplete="off"
           type="search"
           class="form-control rounded"
           placeholder='Search (ctrl + "/" to focus)'
           style="min-width: 225px"
           />
    <span class="input-group-text border-0"
          ><i class="fas fa-search"></i
      ></span>
  </form>

  <!-- Right links -->
  <ul class="navbar-nav ms-auto d-flex flex-row">
    <!-- Notification dropdown -->
    <li class="nav-item dropdown">
      <a
         class="nav-link me-3 me-lg-0 dropdown-toggle hidden-arrow"
         href="#"
         id="navbarDropdownMenuLink"
         role="button"
         data-mdb-toggle="dropdown"
         aria-expanded="false"
         >
        <i class="fas fa-bell"></i>
        <span class="badge rounded-pill badge-notification bg-danger"
              >1</span
          >
      </a>
      <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="navbarDropdownMenuLink"
          >
        <li><a class="dropdown-item" href="#">Some news</a></li>
        <li><a class="dropdown-item" href="#">Another news</a></li>
        <li>
          <a class="dropdown-item" href="#">Something else here</a>
        </li>
      </ul>
    </li>

    <!-- Icon -->
    
    <!-- Icon -->
    <li class="nav-item me-3 me-lg-0">
      <a class="nav-link" href="#">
        <i class="fab fa-github"></i>
      </a>
    </li>

    
    <!-- Avatar -->
    <li class="nav-item dropdown">
      <a
         class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center"
         href="#"
         id="navbarDropdownMenuLink"
         role="button"
         data-mdb-toggle="dropdown"
         aria-expanded="false"
         >
        <img
             src="https://mdbootstrap.com/img/Photos/Avatars/img (31).jpg"
             class="rounded-circle"
             height="22"
             alt=""
             loading="lazy"
             />
      </a>
      <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="navbarDropdownMenuLink"
          >
        <li><a class="dropdown-item" href="#">My profile</a></li>
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><a class="dropdown-item" href="#">Logout</a></li>
      </ul>
    </li>
  </ul>
</div>
<!-- Container wrapper -->
</nav>

Employee/templates/kitadd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Kit</title>
    {% extends 'sidebar.html' %}
</head>
<body class="container-fluid">
    {% block content %}
    
   <form action="{% url 'kitadd' %}" method="post" class="card p-5 bg-light mt-5 col-md-8">
       {% csrf_token %}
       <div class="form-group row">
           <label class="col-sm-1 col-form-label"></label>
           <div class="col-sm-6">
               <h3 class="text-primary">Enter Kit Details</h3>
           </div>
       </div>

       <div class="form-group row">
           <label for="id_first_name" class="col-sm-4 col-form-label">Kit Name</label>
           <div class="col-sm-6">
               {{ form.kit_name }}
           </div>
       </div>
       <div class="form-group row">
           <label for="id_last_name" class="col-sm-4 col-form-label">Player Name</label>
           <div class="col-sm-6">
               {{ form.player_id }}
           </div>
       </div>
       <div class="form-group row">
           <label for="id_age" class="col-sm-4 col-form-label">Collection Date</label>
           <div class="col-sm-6">
               {{ form.collection_date }}
           </div>
       </div>
       <button class="btn btn-primary" type="submit">Submit</button>
   </form>
   {% endblock %}
</body>
</html>

Employee/templates/kitupdate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Player</title>
    {% extends 'sidebar.html' %}
</head>
<body class="container-fluid">
    
{% block content %}
<form action="{% url 'update_kit' kit.kit_id %}" method="post" class="post-form card p-5 bg-light mt-5 col-md-8">
    {% csrf_token %}
    <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-6">
            <h3 class="text-primary">Update Kit Details</h3>
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-4 col-form-label">Kit Name</label>
        <div class="col-sm-6">
            <input type="text" id="id_first_name" name="kit_name" class="form-control" value="{{ kit.kit_name }}">
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-4 col-form-label">Player Name</label>
        <div class="col-sm-6">
            <select class="form-control" name="player_id" required>
                {% for player in players %}
                    <option value="{{ player.player_id }}" {% if player.player_id == kit.player_id %} selected {% endif %}>
                        {{ player.first_name }} {{ player.last_name }}
                    </option>
                {% endfor %}
            </select>
        </div>
    </div>
    
    <div class="form-group row">
        <label for="id_age" class="col-sm-4 col-form-label">Collection Date</label>
        <div class="col-sm-6">
            <input type="date" name="collection_date" class="form-control" value="{{ kit.collection_date|date:'Y-m-d' }}">
        </div>
    </div>
    


    <button class="btn btn-outline-success col-sm-4" type="submit">Save Changes</button>
</form>
{% endblock %}

</body>
</html>

Employee/templates/kitview.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Kits Collection Details's Table</title>
<style>
/* Custom CSS */
.table-striped tbody tr:nth-of-type(odd) {
    background-color: whitesmoke;
}

.table-striped tbody tr:hover {
    background-color: lightgray;
}

.btn-action {
    margin-right: 5px;
}
</style>
{% extends 'sidebar.html' %}
</head>
<body>
{% block content %}
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
{% endif %} 

<div class="container">
    <h2>Kits Collection Details</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Kit ID</th>
                <th>Kit Name</th>
                <th>Player Name</th>
                <th>Collection Date</th>
            </tr>
        </thead>
        <tbody>
            {% for kit in kits %}
            <tr>                
                <td>{{ kit.kit_id }}</td>
                <td>{{ kit.kit_name }}</td>
                <td>{{ kit.player_id }}</td>
                <td>{{ kit.collection_date }}</td>
                <td>
                    <a href="{% url 'update_kit' kit.kit_id %}" class="btn btn-primary">Update</a>
                    <a href="{% url 'delete_kit' kit.kit_id %}" class="btn btn-danger" onclick="confirmDelete('{{ kit.first_name }} {{ kit.last_name }}')">Delete</a>
                </td>
            </tr>          
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'kitadd' %}" class="btn btn-lg btn-outline-primary">Add kit</a>
</div>

<script>
function confirmDelete(kitName) {
    if (confirm("Are you sure you want to delete " + kitName + "?")) {
        // Proceed with deletion
    } else {
        // Cancel deletion
    }
}
</script>

{% endblock %}
</body>
</html>

Employee/templates/nav.html
<section class="row">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-lg navbar-dark  bg-dark ml-4">
        <a href="" class="navbar-brand">Employee Manager</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-Support">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="">Add New Employee</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="">Show Employees</a>
                </li>
            </ul>
        </div>
    </nav>
</section>

Employee/templates/playeradd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Player</title>
    {% extends 'sidebar.html' %}
</head>
<body class="container-fluid">
    {% block content %}
    
   <form action="{% url 'playeradd' %}" method="post" class="card p-5 bg-light mt-5 col-md-8">
       {% csrf_token %}
       <div class="form-group row">
           <label class="col-sm-1 col-form-label"></label>
           <div class="col-sm-6">
               <h3 class="text-primary">Enter Player Details</h3>
           </div>
       </div>

       <div class="form-group row">
           <label for="id_first_name" class="col-sm-4 col-form-label">First Name</label>
           <div class="col-sm-6">
               {{ form.first_name }}
           </div>
       </div>
       <div class="form-group row">
           <label for="id_last_name" class="col-sm-4 col-form-label">Last Name</label>
           <div class="col-sm-6">
               {{ form.last_name }}
           </div>
       </div>
       <div class="form-group row">
           <label for="id_age" class="col-sm-4 col-form-label">Age</label>
           <div class="col-sm-6">
               {{ form.age }}
           </div>
       </div>
       <div class="form-group row">
           <label for="id_address" class="col-sm-4 col-form-label">Address</label>
           <div class="col-sm-6">
               {{ form.address }}
           </div>
       </div>
       <div class="form-group row">
           <label for="id_email" class="col-sm-4 col-form-label">Email</label>
           <div class="col-sm-6">
               {{ form.email }}
           </div>
       </div>
       <div class="form-group row">
           <label for="id_trainer_id" class="col-sm-4 col-form-label">Trainer</label>
           <div class="col-sm-6">
               {{ form.trainer_id }}
           </div>
       </div>
       <div class="form-group row">
           <label for="id_club_id" class="col-sm-4 col-form-label">Club</label>
           <div class="col-sm-6">
               {{ form.club_id }}
           </div>
       </div>
       <div class="form-group row">
           <label for="id_dob" class="col-sm-4 col-form-label">Date of Birth</label>
           <div class="col-sm-6">
               {{ form.dob }}
           </div>
       </div>
       <button class="btn btn-primary" type="submit">Submit</button>
   </form>
   {% endblock %}
</body>
</html>

Employee/templates/playerupdate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Player</title>
    {% extends 'sidebar.html' %}
</head>
<body class="container-fluid">
    
{% block content %}
<form action="{% url 'update_player' player.player_id %}" method="post" class="post-form card p-5 bg-light mt-5 col-md-8">
    {% csrf_token %}
    <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-6">
            <h3 class="text-primary">Update Player Details</h3>
        </div>
    </div>

    <div class="form-group row">
        <label for="id_first_name" class="col-sm-4 col-form-label">First Name</label>
        <div class="col-sm-6">
            <input type="text" id="id_first_name" name="first_name" class="form-control" value="{{ player.first_name }}">
        </div>
    </div>
    <div class="form-group row">
        <label for="id_last_name" class="col-sm-4 col-form-label">Last Name</label>
        <div class="col-sm-6">
            <input type="text" id="id_last_name" name="last_name" class="form-control" value="{{ player.last_name }}">
        </div>
    </div>
    <div class="form-group row">
        <label for="id_age" class="col-sm-4 col-form-label">Age</label>
        <div class="col-sm-6">
            <input type="number" id="id_age" name="age" class="form-control" value="{{ player.age }}">
        </div>
    </div>
    <div class="form-group row">
        <label for="id_address" class="col-sm-4 col-form-label">Address</label>
        <div class="col-sm-6">
            <input type="text" id="id_address" name="address" class="form-control" value="{{ player.address }}">
        </div>
    </div>
    <div class="form-group row">
        <label for="id_email" class="col-sm-4 col-form-label">Email</label>
        <div class="col-sm-6">
            <input type="email" id="id_email" name="email" class="form-control" value="{{ player.email }}">
        </div>
    </div>

    <div class="form-group row">
        <label for="id_trainer_id" class="col-sm-4 col-form-label">Trainer ID</label>
        <div class="col-sm-6">
            <select name="trainer_id" id="id_trainer_id" class="form-control">
                {% for trainer in trainers %}
                    <option value="{{ trainer.id }}" {% if trainer.id == player.trainer_id.id %} selected {% endif %}>{{ trainer.name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-4 col-form-label">Club ID</label>
        <div class="col-sm-6">
            <select name="club_id" class="form-control">
                {% for club in clubs %}
                    <option value="{{ club.clud_id }}" {% if club.clud_id == player.club.club_name %} selected {% endif %}>{{ club.club_name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>


    <div class="form-group row">
        <label for="id_dob" class="col-sm-4 col-form-label">Date of Birth</label>
        <div class="col-sm-6">
            <input type="date" id="id_dob" name="dob" class="form-control" value="{{ player.dob|date:'Y-m-d'  }}">
        </div>
    </div>
    <button class="btn btn-outline-success col-sm-4" type="submit">Save Changes</button>
</form>
{% endblock %}

</body>
</html>